export default {
	// USERs
	GET_ALL_USER : "GET_ALL_USER",
	RECEIVE_GET_ALL_USER : "RECEIVE_GET_ALL_USER",

	GET_SINGLE_USER : "GET_SINGLE_USER",
	RECEIVE_GET_SINGLE_USER : "RECEIVE_GET_SINGLE_USER",

	EDIT_USER: "EDIT_USER",
	RECEIVE_EDIT_USER: "RECEIVE_EDIT_USER",
}