export default {
	// NEWSs
	GET_ALL_NEWS : "GET_ALL_NEWS",
	RECEIVE_GET_ALL_NEWS : "RECEIVE_GET_ALL_NEWS",

	GET_SINGLE_NEWS : "GET_SINGLE_NEWS",
	RECEIVE_GET_SINGLE_NEWS : "RECEIVE_GET_SINGLE_NEWS",

	CREATE_NEWS: "CREATE_NEWS",
	RECEIVE_CREATE_NEWS: "RECEIVE_CREATE_NEWS",

	EDIT_NEWS: "EDIT_NEWS",
	RECEIVE_EDIT_NEWS: "RECEIVE_EDIT_NEWS",

	DELETE_NEWS: "DELETE_NEWS",
	RECEIVE_DELETE_NEWS: "RECEIVE_DELETE_NEWS",
}